version: '3.7'
services:
  nginx:
    build:
      context: nginx/
    volumes:
      - "../web/build/:/usr/share/nginx/html/:ro"
    ports:
      - "80:80"
    networks:
      - internal
networks:
  internal: